# Generated by Django 4.1.3 on 2022-12-08 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0003_alter_forecast_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
