# Generated by Django 4.1.3 on 2022-12-08 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0004_forecast_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecast',
            old_name='created_at',
            new_name='date_added',
        ),
    ]
