# Generated by Django 4.1.3 on 2022-12-09 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0005_rename_created_at_forecast_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecast',
            old_name='country',
            new_name='formatted_address',
        ),
        migrations.RemoveField(
            model_name='forecast',
            name='name',
        ),
    ]
